language: python
python:
 - "2.7"
install:
- sudo apt-get install python-dev
- pip install --upgrade pip 
- pip install -r requirements/local.txt
script:
- python manage.py test apps.tests --settings=hearcloud.settings.local
