---
- hosts: localhost
  sudo: yes
  remote_user: vagrant
  vars:
    db_name: hearcloud
    db_user: dbuser
    db_password:
  tasks:
  - name: Actualizar el sistema
    apt: update_cache=yes upgrade=dist
    sudo: yes

  - name: Establecer variable de sesion presencia de Azure
    command: sudo echo "AZURE=yes" >> /etc/environment

  - name: Instalar python, PostgreSQL y otros paquetes
    action: apt pkg={{ item }} state=present
    sudo: yes
    with_items:
      - python-setuptools
      - build-essential 
      - python-dev
      - libpq-dev 
      - postgresql 
      - postgresql-contrib
      - python-psycopg2
      - libjpeg-dev

  - name: Asegurar que el servicio PostgreSQL está levantado
    service: name=postgresql state=started enabled=yes
    sudo: yes

  - name: Asegurar la creación de la base de datos
    sudo_user: postgres
    postgresql_db: 
      name={{ db_name }}
      encoding='UTF-8'
      lc_collate='en_US.UTF-8'
      lc_ctype='en_US.UTF-8'
      template='template0'
      state=present

  - name: Asegurar que el usuario tiene acceso a la base de datos
    sudo_user: postgres
    postgresql_user: 
      db={{ db_name }}
      name={{ db_user }}
      password={{ db_password }}
      priv=ALL
      state=present

  - name: Asegurar que el usuario no tiene privilegios innecesarios
    sudo_user: postgres
    postgresql_user: 
      name={{ db_user }}
      role_attr_flags=NOSUPERUSER,NOCREATEDB
      state=present

  - name: Instalar git
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    sudo: yes
    with_items:
    - git

  - name: Instalar pip
    command: sudo easy_install pip

  - name: Actualizar pip
    command: pip install --upgrade pip

  - name: Instalar servidor wsgi Gunicorn
    command: sudo pip install gunicorn

  - name: Instalar nginx y supervisor
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    sudo: yes
    with_items:
    - nginx
    - supervisor 

  - name: Obtener la aplicacion de Github
    git: repo=https://github.com/mpvillafranca/hear-cloud.git  dest=hear-cloud clone=yes force=yes

  - name: Permisos de ejecucion
    command: chmod -R +x hear-cloud

  - name: Instalar dependencias de la aplicacion
    command: sudo pip install -r hear-cloud/requirements.txt

  - name: Directorio para servir archivos estaticos con nginx
    command: sudo mkdir -p /var/www
    command: sudo cp -r hear-cloud/static/ /var/www/
    command: sudo cp -r hear-cloud/media/ /var/www/ 
    
  - name: Copiar configuracion de supervisor
    command: sudo mv hear-cloud/vagrant-azure/production-webconfig/supervisor.conf /etc/supervisor/conf.d/

  - name: Copiar configuracion de nginx
    command: sudo mv hear-cloud/vagrant-azure/production-webconfig/default /etc/nginx/sites-available/

  - name: Realizar las migraciones de la base de datos
    command: sudo python hear-cloud/manage.py migrate

  - name: Reiniciar supervisor
    sudo: yes
    service: name=sumervisor state=restarted enabled=true

  - name: Reiniciar Nginx
    sudo: yes
    service: name=nginx state=restarted enabled=true
