---
- hosts: localhost
  remote_user: vagrant
  become: yes
  become_method: sudo
  vars:
    db_name: hearcloud
  tasks:
  - name: Actualizar repositorios de paquetes
    apt: update_cache=yes
    
  - name: Instalar python, PostgreSQL y otros paquetes
    action: apt pkg={{ item }} state=present
    with_items:
      - python-setuptools
      - build-essential 
      - python-dev
      - libpq-dev 
      - postgresql 
      - postgresql-contrib
      - python-psycopg2
      - libjpeg-dev
      - git
      - nginx
      - supervisor 
    
  - name: Instalar pip
    easy_install: name=pip
    
  - name: Instalar servidor wsgi Gunicorn
    pip: name=gunicorn 
    
  - name: Creación de la base de datos especificada en las variables
    become_user: postgres
    postgresql_db: name={{ db_name }}
    
  - name: Creación del usuario de base de datos especificado con los privilegios adecuados
    become_user: postgres
    postgresql_user: 
      db={{db_name}}
      name=dbuser
      password=12345678
      priv=ALL
      role_attr_flags=NOSUPERUSER,NOCREATEDB
      state=present
         
  - name: Obtener la aplicacion de Github
    become_user: vagrant
    git: repo=https://github.com/mpvillafranca/hear-cloud.git  dest=/home/vagrant/hear-cloud clone=yes force=yes
    
  - name: Instalar dependencias de la aplicacion
    become_user: vagrant
    pip: requirements=/home/vagrant/hear-cloud/requirements.txt
