# -*- mode: ruby -*-

Vagrant.configure(2) do |config|

  # Box Settings
  config.vm.box = "azure"
  config.vm.box_url = 'https://github.com/msopentech/vagrant-azure/raw/master/dummy.box'
  
  # VM Network Settings
  config.vm.network "public_network"
  config.vm.define "localhost" do |l|
          l.vm.hostname = "localhost"
  end

  config.vm.provider :azure do |azure, override|
    # Mandatory Settings 
    azure.mgmt_certificate = '2ef4708d-b747-46b3-bee6-a75d47f2ee62.pem'
    azure.mgmt_endpoint = 'https://management.core.windows.net'
    azure.subscription_id = '2ef4708d-b747-46b3-bee6-a75d47f2ee62'
    azure.vm_image = 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_3-LTS-amd64-server-20160201-en-us-30GB'
    azure.vm_name = 'hearcloud' # max 15 characters. contains letters, number and hyphens. can start with letters and can end with letters and numbers

    # vm_password is optional when specifying the private_key_file with Linux VMs
    # When building a Windows VM and using WinRM this setting is used to authenticate via WinRM (PowerShell Remoting)
    azure.vm_password = 'Mariano94!' # min 8 characters. should contain a lower case letter, an uppercase letter, a number and a special character

    # Optional Settings
    azure.vm_location = 'East Asia' # e.g., West US

    # Open ports for web server
    azure.tcp_endpoints = '80:80'
    end

    # Provisioning machine
    config.vm.provision "ansible" do |ansible|
	    ansible.sudo = true
        ansible.playbook = "hearcloud.yml"
	    ansible.verbose = "vvv"
  end
end
