# -*- mode: ruby -*-
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'azure'
  config.vm.network "public_network"
  config.vm.define "localhost" do |l|
	l.vm.hostname = "localhost"
  end
    
  config.vm.provider :azure do |azure|
    azure.mgmt_certificate = File.expand_path('~/vagrant-azure.pem')
    azure.mgmt_endpoint = 'https://management.core.windows.net'
    azure.subscription_id = '2ef4708d-b747-46b3-bee6-a75d47f2ee62'
    azure.vm_image = 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_3-LTS-amd64-server-20160201-en-us-30GB'
    azure.vm_name = 'hearcloud'
    azure.vm_user = 'hearclouduser'
    azure.vm_password = '12345'
    azure.vm_location = 'East Asia' 
    azure.cloud_service_name = 'hearcloud'
    azure.ssh_port = '22'
    azure.tcp_endpoints = '80:80'
  end
  
  config.ssh.username = 'hearclouduser' 
  config.ssh.password = '12345'

  config.vm.provision "ansible" do |ansible|
	ansible.sudo = true
    ansible.playbook = "ansible-azure.yml"
	ansible.verbose = "v"
	ansible.host_key_checking = false 
  end
end
